name: CI Pipeline

on:
  push:

jobs:

  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test add
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./src/calculator add 10 5

  Test_Sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test sub
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./src/calculator sub 3 -2

  Test_Mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test mul
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./src/calculator mul 5 5

  Test_Div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test div
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./src/calculator div 1 5

  Test_Car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test car
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./src/calculator car 5

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Test_Add
      - Test_Sub
      - Test_Mul
      - Test_Div
      - Test_Car
    steps:
      - name: Deploy
        run: echo "Déploiement de la solution"